export const Colors = {
  light: {
    primary: '#eef4ff',
    secondary: '#dbeafe',
    accent: '#2563eb',
    safeArea: '#eef4ff',
    background: '#f8fafc',
    gradient: ['#eef4ff', '#dbeafe', '#bfdbfe'],
    card: '#ffffff',
    border: '#cbd5e1',
    text: '#0f172a',
    subtext: '#475569',
    cardText: '#0f172a',
    link: '#1d4ed8',
    headerBackground: '#eff6ff',
    headerTint: '#0f172a',
    statusBar: 'dark',
    toggleButtonBackground: '#1d4ed8',
    toggleButtonBorder: '#1d4ed8',
    toggleButtonText: '#ffffff',
  },
  dark: {
    primary: '#0f172a',
    secondary: '#1e293b',
    accent: '#38bdf8',
    safeArea: '#0b1120',
    background: '#111827',
    gradient: ['#312e81', '#1e3a8a', '#0f766e'],
    card: '#0f2942',
    border: '#2a445d',
    text: '#f8fafc',
    subtext: '#cbd5e1',
    cardText: '#f8fafc',
    link: '#93c5fd',
    headerBackground: '#111827',
    headerTint: '#f8fafc',
    statusBar: 'light',
    toggleButtonBackground: '#e0f2fe',
    toggleButtonBorder: '#7dd3fc',
    toggleButtonText: '#082f49',
  },
};
